# Generated by Django 2.0 on 2018-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
