# Generated by Django 2.0 on 2018-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180105_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='posts/img', verbose_name='фотография'),
        ),
    ]
