# Generated by Django 2.0 on 2018-01-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180105_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='description',
        ),
        migrations.AddField(
            model_name='posts',
            name='city',
            field=models.CharField(default='Оренбург', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='posts',
            name='country',
            field=models.CharField(default='Россия', max_length=50, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='posts',
            name='date_night',
            field=models.CharField(default='16 янв, 6 ночей', max_length=50, verbose_name='Дата вылета/кол-во ночей'),
        ),
        migrations.AddField(
            model_name='posts',
            name='first_cena',
            field=models.IntegerField(default='50000', verbose_name='Цена без учета акции'),
        ),
        migrations.AddField(
            model_name='posts',
            name='last_cena',
            field=models.IntegerField(default='20000', verbose_name='Цена с учетом акции'),
        ),
        migrations.AddField(
            model_name='posts',
            name='skidka',
            field=models.IntegerField(default='49', verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='posts',
            name='star',
            field=models.IntegerField(default='5', max_length=2, verbose_name='Количество звезд'),
        ),
        migrations.AddField(
            model_name='posts',
            name='vilet',
            field=models.CharField(default='15 янв', max_length=50, verbose_name='Город вылета'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='posts/img', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Название тура'),
        ),
    ]
