# Generated by Django 2.0 on 2018-01-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180108_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='star',
            field=models.IntegerField(default='5', verbose_name='Количество звезд'),
        ),
    ]
