# Generated by Django 2.0 on 2018-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180108_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='vilet',
            field=models.CharField(default='Оренбург', max_length=50, verbose_name='Город вылета'),
        ),
    ]
