# Generated by Django 2.0 on 2018-01-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180108_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='first_cena',
            field=models.IntegerField(blank=True, default='', verbose_name='Цена без учета скидки'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='last_cena',
            field=models.IntegerField(default='20000', verbose_name='Цена с учетом скидки'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(default='', upload_to='posts/img', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='skidka',
            field=models.IntegerField(blank=True, default='', verbose_name='Процент скидки'),
        ),
    ]
