# Generated by Django 2.0 on 2018-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180108_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='first_cena',
            field=models.IntegerField(default='', verbose_name='Цена без учета скидки'),
        ),
    ]
