# Generated by Django 2.0 on 2018-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180108_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='last_cena',
            field=models.IntegerField(verbose_name='Цена с учетом скидки'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='skidka',
            field=models.IntegerField(default='', verbose_name='Процент скидки'),
        ),
    ]
