# Generated by Django 2.0 on 2018-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180108_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='body',
        ),
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.TextField(default='Комментарии наших менеджеров'),
        ),
        migrations.AddField(
            model_name='posts',
            name='persons',
            field=models.CharField(default='2 взрослых', max_length=50, verbose_name='Кол-во человек'),
        ),
        migrations.AddField(
            model_name='posts',
            name='program_tura',
            field=models.CharField(default='', max_length=150, verbose_name='Программа тура'),
        ),
        migrations.AddField(
            model_name='posts',
            name='tour_meal',
            field=models.CharField(default='RO - Без питания', max_length=150, verbose_name='Тип питания в отеле'),
        ),
        migrations.AddField(
            model_name='posts',
            name='tour_room',
            field=models.CharField(default='2-местный стандарт 2 категории', max_length=150, verbose_name='Описание номера в отеле'),
        ),
        migrations.AddField(
            model_name='posts',
            name='type_otdyh',
            field=models.CharField(default='Активный отдых', max_length=100, verbose_name='Тип питания в отеле'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(default='', upload_to='posts/img', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='vilet',
            field=models.CharField(default='Оренбурга', max_length=50, verbose_name='Город вылета'),
        ),
    ]
