# Generated by Django 2.0 on 2018-01-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180110_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='beach',
            field=models.TextField(blank=True, verbose_name='Пляж'),
        ),
        migrations.AddField(
            model_name='posts',
            name='common_info',
            field=models.TextField(blank=True, verbose_name='Общая информация'),
        ),
        migrations.AddField(
            model_name='posts',
            name='concept_food',
            field=models.TextField(blank=True, verbose_name='Концепция питания'),
        ),
        migrations.AddField(
            model_name='posts',
            name='for_children',
            field=models.TextField(blank=True, verbose_name='Для детей'),
        ),
        migrations.AddField(
            model_name='posts',
            name='free_services',
            field=models.TextField(blank=True, verbose_name='Бесплатные услуги'),
        ),
        migrations.AddField(
            model_name='posts',
            name='in_hotel',
            field=models.TextField(blank=True, verbose_name='В номере'),
        ),
        migrations.AddField(
            model_name='posts',
            name='pay_services',
            field=models.TextField(blank=True, verbose_name='Платные услуги'),
        ),
        migrations.AddField(
            model_name='posts',
            name='services',
            field=models.TextField(blank=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='posts',
            name='territory',
            field=models.TextField(blank=True, verbose_name='Территория отеля'),
        ),
        migrations.AddField(
            model_name='posts',
            name='type_hotel',
            field=models.TextField(blank=True, verbose_name='Типы номеров'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии наших менеджеров'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='program_tura',
            field=models.CharField(default='Краснодарский край (а/п Адлер)', max_length=150, verbose_name='Программа тура'),
        ),
    ]
