# Generated by Django 2.0 on 2018-01-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20180110_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='valute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.CharField(default='56,8734', max_length=80)),
                ('evro', models.CharField(default='67,8841', max_length=80)),
            ],
        ),
    ]
