# Generated by Django 2.0 on 2018-01-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_valute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='valute',
        ),
    ]
