# Generated by Django 2.0 on 2018-01-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_delete_valute'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ImageField(default='', upload_to='posts/img', verbose_name='Кртинки полной статьи'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='type_otdyh',
            field=models.CharField(default='Активный отдых', max_length=100, verbose_name='Тип отдыха'),
        ),
    ]
