# Generated by Django 2.0 on 2018-01-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20180113_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageposts',
            name='imageposts',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.posts'),
        ),
    ]
