# Generated by Django 2.0.6 on 2018-06-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80, verbose_name='Наименование курса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.CharField(default='', max_length=180, verbose_name='Цена')),
                ('hours', models.CharField(default='', max_length=180, verbose_name='Часы')),
                ('background', models.ImageField(default='', upload_to='annex/img/%Y/%m/%d', verbose_name='Фон')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Events_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80, verbose_name='Наименование мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_push', models.DateTimeField(verbose_name='Дата провендения')),
                ('background', models.ImageField(default='', upload_to='annex/img/%Y/%m/%d', verbose_name='Фон')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='annex/img/avatar_big.png', null=True, upload_to='annex/img/%Y/%m/%d', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
