# Generated by Django 2.0.4 on 2018-04-24 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название компании')),
                ('city', models.CharField(max_length=80, verbose_name='Город')),
                ('background', models.ImageField(default='', upload_to='annex/img/%Y/%m/%d', verbose_name='Фон')),
            ],
            options={
                'verbose_name': 'Все компании',
                'verbose_name_plural': 'Все компании',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='annex/img/avatar_big.png', null=True, upload_to='annex/img/%Y/%m/%d', verbose_name='Аватар')),
                ('role', models.CharField(choices=[('D', 'Директор'), ('P', 'Директор - партнер'), ('M', 'Менеджер')], default='Директор - партнер', max_length=1, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
