# Generated by Django 2.0.4 on 2018-05-23 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='ООО СТРОИТЕЛЬНАЯ КОМПАНИЯ «Дома в Оренбурге»', max_length=180, verbose_name='Полное наименование компании')),
                ('name', models.CharField(default='Тимфорт', max_length=80, verbose_name='Краткое название компании')),
                ('adress', models.CharField(default='г. Оренбург, Россия, 460006', max_length=180, verbose_name='Адрес')),
                ('phone', models.CharField(default='(3532) 37-62-97', max_length=180, verbose_name='Телефон')),
                ('email', models.CharField(default='manager@doma-v-orenburge.ru', max_length=180, verbose_name='Электронная почта')),
                ('background', models.ImageField(default='', upload_to='annex/img/%Y/%m/%d', verbose_name='Фон')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Все компании',
                'verbose_name_plural': 'Все компании',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Тимфорт', max_length=80, verbose_name='Наименование завода')),
                ('adress', models.CharField(default='г. Оренбург, Россия, 460006', max_length=180, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Все заводы',
                'verbose_name_plural': 'Все заводы',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=180, verbose_name='Наименование спецификации проекта')),
                ('composition', models.TextField(verbose_name='Состав работ и затрат')),
                ('unit', models.CharField(default='', max_length=30, verbose_name='Ед. изм')),
                ('price', models.CharField(default='', max_length=20, verbose_name='Цена за ед.')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annex.Company', verbose_name='Компания')),
                ('factory_associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annex.Factory', verbose_name='Завод')),
            ],
            options={
                'verbose_name': 'Заявки на изготовление',
                'verbose_name_plural': 'Заявки на изготовление',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='annex/img/avatar_big.png', null=True, upload_to='annex/img/%Y/%m/%d', verbose_name='Аватар')),
                ('role', models.CharField(choices=[('M', 'Менеджер'), ('P', 'Директор - партнер'), ('D', 'Директор')], default='Директор - партнер', max_length=1, verbose_name='Роль')),
                ('associate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='annex.Company', verbose_name='Компания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=180, verbose_name='Наименование')),
                ('composition', models.TextField(verbose_name='Состав работ и затрат')),
                ('unit', models.CharField(default='', max_length=30, verbose_name='Ед. изм')),
                ('price', models.CharField(default='', max_length=20, verbose_name='Цена за ед.')),
                ('associate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='annex.Company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Виды работ компании',
                'verbose_name_plural': 'Виды работ компании',
            },
        ),
    ]
