# Generated by Django 2.0.6 on 2018-06-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events_admin',
            new_name='EventAdmin',
        ),
    ]
