# Generated by Django 2.0.4 on 2018-05-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='date',
            new_name='date_push',
        ),
    ]
