# Generated by Django 2.0.4 on 2018-04-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0002_profile_associate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='associate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Компания', to='annex.Company'),
        ),
    ]
