# Generated by Django 2.0.6 on 2018-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(default='', upload_to='annex/img/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='Наименование новости'),
        ),
    ]
