# Generated by Django 2.0.4 on 2018-04-24 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0003_auto_20180424_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Сотрудник', to=settings.AUTH_USER_MODEL),
        ),
    ]
