# Generated by Django 2.0.4 on 2018-05-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0003_auto_20180524_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Спецификация', 'verbose_name_plural': 'Спецификация'},
        ),
        migrations.AddField(
            model_name='materials',
            name='amount',
            field=models.CharField(default='', max_length=10, verbose_name='Объем изделия, м3'),
        ),
        migrations.AddField(
            model_name='materials',
            name='area',
            field=models.CharField(default='', max_length=10, verbose_name='Площадь штукатурки,м2'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='weight',
            field=models.CharField(default='', max_length=10, verbose_name='Толщина'),
        ),
    ]
