# Generated by Django 2.0.6 on 2018-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0004_auto_20180618_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryadmin',
            name='name',
            field=models.CharField(default='', max_length=80, verbose_name='Наименование картинки'),
        ),
    ]
