# Generated by Django 2.0.4 on 2018-05-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0004_auto_20180524_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='date_push',
        ),
    ]
