# Generated by Django 2.0.4 on 2018-04-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0005_auto_20180424_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('M', 'Менеджер'), ('P', 'Директор - партнер'), ('D', 'Директор')], default='Директор - партнер', max_length=1, verbose_name='Роль'),
        ),
    ]
