# Generated by Django 2.0.4 on 2018-06-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0006_auto_20180603_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='user',
        ),
    ]
