# Generated by Django 2.0.4 on 2018-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0007_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.AddField(
            model_name='company',
            name='adress',
            field=models.CharField(default='г. Оренбург, Россия, 460006', max_length=180, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='manager@doma-v-orenburge.ru', max_length=180, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='(3532) 37-62-97', max_length=180, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Наименование компании'),
        ),
    ]
