# Generated by Django 2.0.4 on 2018-06-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0008_specification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='factory_associate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='annex.Factory', verbose_name='Завод'),
        ),
    ]
