# Generated by Django 2.0.4 on 2018-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0008_auto_20180430_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(default='ООО СТРОИТЕЛЬНАЯ КОМПАНИЯ «Дома в Оренбурге»', max_length=180, verbose_name='Полное наименование компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Тимфорт', max_length=80, verbose_name='Краткое название компании'),
        ),
    ]
