# Generated by Django 2.0.4 on 2018-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0009_profile_factory_associate'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='background',
            field=models.ImageField(default='', upload_to='annex/img/%Y/%m/%d', verbose_name='Фон'),
        ),
    ]
