# Generated by Django 2.0.4 on 2018-04-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0010_auto_20180430_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=180, verbose_name='Наименование')),
                ('composition', models.TextField(blank=True, verbose_name='Состав работ и затрат')),
                ('unit', models.CharField(default='', max_length=30, verbose_name='Ед. изм')),
                ('price', models.CharField(default='', max_length=20, verbose_name='Цена за ед.')),
                ('count', models.CharField(default='', max_length=10, verbose_name='Кол-во')),
                ('amount', models.CharField(default='', max_length=180, verbose_name='Сумма')),
                ('associate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='annex.Company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Виды работ компании',
                'verbose_name_plural': 'Виды работ компании',
            },
        ),
    ]
