# Generated by Django 2.0.4 on 2018-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0010_factory_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Менеджер', 'Менеджер'), ('Логист', 'Логист'), ('Завод', 'Завод'), ('Директор - партнер', 'Директор - партнер'), ('Директор', 'Директор')], default='Логист', max_length=1, verbose_name='Роль'),
        ),
    ]
