# Generated by Django 2.0.4 on 2018-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0011_auto_20180612_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('M', 'Менеджер'), ('L', 'Логист'), ('Z', 'Завод'), ('P', 'Директор - партнер'), ('D', 'Директор')], default='Логист', max_length=1, verbose_name='Роль'),
        ),
    ]
