# Generated by Django 2.0.4 on 2018-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0011_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='work',
            name='count',
        ),
        migrations.AlterField(
            model_name='work',
            name='composition',
            field=models.TextField(verbose_name='Состав работ и затрат'),
        ),
    ]
