# Generated by Django 2.0.4 on 2018-06-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0012_auto_20180612_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(default='', max_length=80, verbose_name='Кол-во выполненных')),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annex.Materials', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Выполненные материалы',
                'verbose_name_plural': 'Выполненные материалы',
            },
        ),
    ]
