# Generated by Django 2.0.4 on 2018-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0014_auto_20180612_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='area',
            field=models.CharField(default='', max_length=10, verbose_name='Площадь штукатурки, м2'),
        ),
    ]
