# Generated by Django 2.0.4 on 2018-06-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0015_auto_20180612_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edit_materials',
            new_name='Editmaterials',
        ),
    ]
